server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://bitbucket.domain.com/tfs/EDW/department/_git/EdaCoreConfigRepo
          ignoreLocalSshSettings: true
          private-key: |
                       -----BEGIN RSA PRIVATE KEY-----
                    abc13ABC123......................
                       -----END RSA PRIVATE KEY-----
security:
    basic:
        enabled: false
management:
  security:
    enabled: false


